### PR TITLE
Config with default template

### PR DESCRIPTION
**Pull request by gforcada**
Base changes needed for #13 which will include the testing part, here we are not adding it, as testing is done with `pytest` and that's #13 task 😄

### CODE REVIEW

**Comment by gforcada** [comment]
🗒️ once this is merged, this repository needs to be added on the [linting global workflow](https://github.com/organizations/plone/settings/actions)

**Review by mauritsvanrees — APPROVED** [review]
LGTM

@jenkins-plone-org please run jobs

**Comment by mauritsvanrees** [comment]
@jenkins-plone-org please run jobs

**Comment by mauritsvanrees** [comment]
One unrelated failure in plone.app.querystring.

**Comment by mauritsvanrees** [comment]
I added borg.localrole to the linting workflows.

**Pull request merged**
